### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Darkmet98** [Darkmet98/Pleinair#1]
### To 1.0

- [x] Export only the strings to translate
- [x] Remove the first line of bytes
- [x] Export the strings from the Disgaea 1 PC Executable
- [x] Import the strings from the Disgaea 1 PC Executable
- [x] Port to Net Core 3.
- [x] Add custom exceptions to the program.
- [x] Fix bad FAD import on linux
- [x] Refactor program.cs
- [x] Update the credits
- [x] Add savefile strings from Disgaea 1 PC Executable
